In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
a2 = np.array([
    [1, 2],
    [2, 4]
])

a2

array([[1, 2],
       [2, 4]])

In [7]:
a2.shape

(2, 2)

In [8]:
a3 = np.array([
    [[1, 2], [3, 4] , [3, 4]],
    [[5, 6], [7, 8] , [3, 4]] ,
    [[5, 6], [7, 8] , [3, 4]] ,
    [[5, 6], [7, 8] , [3, 4]] ,
    [[5, 6], [7, 8] , [3, 4]] 
])

# axis 1 -  row
# axis 2 - column
# axis 3 - dimentions


a3.shape

(5, 3, 2)

In [9]:
a2.dtype

dtype('int32')

In [10]:
a3.size

30

In [11]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1
0  1  2
1  2  4

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
range = np.arange(0, 10, 2)
range

array([0, 2, 4, 6, 8])

In [15]:
rand = np.random.randint(100, 200, size= (5,5,5))
rand

array([[[143, 141, 162, 169, 155],
        [116, 138, 104, 174, 102],
        [171, 130, 123, 100, 192],
        [180, 125, 187, 159, 183],
        [190, 119, 137, 160, 134]],

       [[103, 153, 122, 131, 174],
        [179, 134, 187, 110, 183],
        [174, 195, 155, 111, 181],
        [102, 170, 141, 110, 182],
        [129, 139, 147, 189, 110]],

       [[127, 149, 149, 177, 123],
        [150, 111, 168, 142, 145],
        [153, 126, 129, 184, 148],
        [121, 133, 136, 167, 136],
        [115, 161, 128, 169, 104]],

       [[135, 125, 170, 192, 170],
        [189, 117, 187, 126, 108],
        [106, 105, 162, 158, 136],
        [170, 134, 186, 190, 136],
        [104, 112, 157, 155, 180]],

       [[181, 127, 143, 155, 185],
        [127, 120, 154, 150, 109],
        [108, 124, 131, 194, 161],
        [116, 108, 111, 144, 137],
        [169, 193, 141, 177, 134]]])

In [27]:
# rand.see is psudo-random give the same random value, making it reproducable
np.random.seed(seed=99)

rand_seed = np.random.randint(1, 5, size= (5,3))
rand_seed

array([[2, 4, 2],
       [1, 2, 1],
       [3, 1, 2],
       [1, 2, 4],
       [3, 4, 4]])

In [31]:
a1 = np.array([1,2,3,3])
a1 = np.unique(a1)
a1

array([1, 2, 3])

In [34]:
a100 = np.random.randint(10, size=(2,3,4,5))
a100

array([[[[3, 3, 6, 1, 0],
         [9, 2, 4, 4, 3],
         [3, 7, 7, 6, 1],
         [0, 5, 3, 4, 7]],

        [[9, 4, 0, 8, 4],
         [6, 8, 4, 3, 6],
         [2, 7, 8, 1, 9],
         [8, 4, 7, 4, 5]],

        [[4, 9, 3, 6, 8],
         [9, 8, 4, 4, 5],
         [3, 6, 6, 9, 8],
         [1, 9, 5, 0, 4]]],


       [[[5, 8, 5, 8, 3],
         [1, 7, 1, 5, 6],
         [4, 0, 3, 0, 2],
         [5, 8, 2, 6, 8]],

        [[8, 9, 1, 8, 1],
         [8, 3, 2, 8, 4],
         [9, 2, 2, 1, 4],
         [1, 3, 3, 8, 8]],

        [[6, 1, 3, 9, 4],
         [5, 7, 3, 8, 2],
         [5, 7, 9, 0, 5],
         [5, 4, 4, 3, 4]]]])

In [46]:
# get the first 4 numbers of the inner most array
a100[:2,:,:, :3]

array([[[[3, 3, 6],
         [9, 2, 4],
         [3, 7, 7],
         [0, 5, 3]],

        [[9, 4, 0],
         [6, 8, 4],
         [2, 7, 8],
         [8, 4, 7]],

        [[4, 9, 3],
         [9, 8, 4],
         [3, 6, 6],
         [1, 9, 5]]],


       [[[5, 8, 5],
         [1, 7, 1],
         [4, 0, 3],
         [5, 8, 2]],

        [[8, 9, 1],
         [8, 3, 2],
         [9, 2, 2],
         [1, 3, 3]],

        [[6, 1, 3],
         [5, 7, 3],
         [5, 7, 9],
         [5, 4, 4]]]])

# Maniuplating arrays

In [58]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [59]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [60]:
rands = np.random.randint(1,3, size=(1,3))
rands

array([[1, 2, 2]])

In [63]:
np.add(ones, rands)

array([[2., 3., 3.]])

In [61]:
ones + rands

array([[2., 3., 3.]])

In [62]:
ones - rands

array([[ 0., -1., -1.]])