In [25]:
import numpy as np

In [6]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [9]:
type(a1)

numpy.ndarray

In [10]:
a1.shape

(3,)

In [13]:
a2 = np.array([
    [1, 2],
    [2, 4]
])

a2

array([[1, 2],
       [2, 4]])

In [15]:
a2.shape

(2, 2)

In [27]:
a3 = np.array([
    [[1, 2], [3, 4] , [3, 4]],
    [[5, 6], [7, 8] , [3, 4]] ,
    [[5, 6], [7, 8] , [3, 4]] ,
    [[5, 6], [7, 8] , [3, 4]] ,
    [[5, 6], [7, 8] , [3, 4]] 
])

# axis 1 -  row
# axis 2 - column
# axis 3 - dimentions


a3.shape

(5, 3, 2)

In [29]:
a2.dtype

dtype('int32')

In [31]:
a3.size

30

In [39]:
import pandas as pd

df = pd.DataFrame(a2)
df

0  1
0  1  2
1  2  4

In [42]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
range = np.arange(0, 10, 2)
range

array([0, 2, 4, 6, 8])

In [59]:
rand = np.random.randint(100, 200, size= (5,5,5))
rand

array([[[165, 146, 127, 134, 149],
        [197, 151, 161, 153, 189],
        [108, 122, 193, 101, 153],
        [172, 136, 185, 185, 195],
        [103, 190, 189, 175, 115]],

       [[155, 165, 127, 184, 118],
        [167, 107, 129, 163, 170],
        [187, 166, 164, 162, 175],
        [123, 113, 102, 142, 139],
        [195, 195, 104, 129, 174]],

       [[167, 179, 100, 127, 154],
        [180, 103, 176, 138, 185],
        [171, 187, 187, 191, 126],
        [192, 150, 117, 140, 108],
        [180, 196, 121, 194, 170]],

       [[159, 180, 101, 132, 127],
        [154, 122, 177, 189, 129],
        [120, 182, 127, 137, 142],
        [152, 195, 105, 131, 150],
        [149, 160, 172, 162, 162]],

       [[132, 149, 151, 172, 171],
        [128, 121, 144, 101, 144],
        [138, 192, 165, 160, 171],
        [158, 184, 176, 139, 155],
        [189, 177, 185, 186, 133]]])